window.otoPatchV010=function(html){
// v0.10.1 — ceremony audio, centered learning feedback, retry queue, body-return misses,
// 2.5D knockdown, intentional TIME pass-through, and a separate competition-info feed.
const marker="$('#start').addEventListener('click',start);";
html=html.replace("v0.9 PRACTICE → TIME → 礼 → HAJIME","v0.10 PRACTICE → TIME → 礼 → HAJIME");
html=html.replace("version:'0.9.0-time-rei-hajime'","version:'0.10.1-sport-feed-time-pass'");
html=html.replace("p=state.mode==='ready'?0:Math.min(1.18,state.flight/state.duration);","p=state.mode==='ready'?0:Math.min((typeof ceremony!=='undefined'&&ceremony==='time')?1.58:1.18,state.flight/state.duration);");
html=html.replace('<small id="hpValue">体力 100 / 100</small>','<small id="hpValue">体力 100 / 100</small><div id="sportFeed" class="sport-feed" aria-live="polite" aria-label="競技情報"></div>');
html=html.replace("body.reduced-motion .symbols button.tutorial-target{animation:none}","body.reduced-motion .symbols button.tutorial-target{animation:none}.practice-card.answer-card{border-color:#9fd8bd;background:#102b28ed;box-shadow:0 5px 18px #0004,0 0 22px #9fd8bd22}.practice-card.answer-card small{color:#f1c883}#arena.body-hit{box-shadow:inset 0 0 0 3px #e9c58b}.sport-feed{display:flex;flex-direction:column;align-items:flex-start;gap:3px;min-height:42px;max-width:330px;margin-top:7px;overflow:visible}.sport-item{display:flex;align-items:baseline;gap:8px;min-height:16px;opacity:0;transform:translateX(-10px);transition:opacity .16s ease,transform .16s ease;text-shadow:0 1px 4px #132b2a;white-space:nowrap}.sport-item.show{opacity:1;transform:translateX(0)}.sport-item.leave{opacity:0;transform:translateY(-4px)}.sport-item b{font-size:14px;letter-spacing:.1em;font-weight:650;color:#fff5d9}.sport-item span{font-size:10px;letter-spacing:.05em;color:#c7d8cf}.sport-item.perfect b{color:#bff0d6}.sport-item.miss b,.sport-item.down b{color:#ffd0b5}.sport-item.down b{font-size:16px}.sport-item.practice b{color:#f1c883}@media(max-width:680px){.sport-feed{max-width:240px;min-height:36px;margin-top:5px}.sport-item{gap:5px}.sport-item b{font-size:12px}.sport-item span{font-size:9px;max-width:150px;overflow:hidden;text-overflow:ellipsis}.sport-item:nth-child(n+3){display:none}}");
const v010=`
const WORD_IPA_V010={think:'/θɪŋk/',thin:'/θɪn/',thank:'/θæŋk/',three:'/θriː/',bath:'/bæθ/',mouth:'/maʊθ/',this:'/ðɪs/',that:'/ðæt/',these:'/ðiːz/',those:'/ðoʊz/',mother:'/ˈmʌðər/',weather:'/ˈwɛðər/',ship:'/ʃɪp/',shop:'/ʃɑp/',she:'/ʃiː/',shoe:'/ʃuː/',fish:'/fɪʃ/',wash:'/wɑʃ/',vision:'/ˈvɪʒən/',measure:'/ˈmɛʒər/',usual:'/ˈjuːʒuəl/',pleasure:'/ˈplɛʒər/',decision:'/dɪˈsɪʒən/',television:'/ˈtɛləˌvɪʒən/'};
let answerCardTimerV010=0,answerCardCorrectV010=true,retryQueueV010=[],questionSerialV010=0,consecutiveFailsV010=0,bodyHitV010=0,knockdownV010=0,knockDirV010=1;
let lastSportKeyV010='',lastSportAtV010=0;
const KNOCKDOWN_DURATION_V010=1.28;
function speakCallV010(text){if(!text||!('speechSynthesis' in window))return;try{window.speechSynthesis.cancel();window.speechSynthesis.resume();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.72;u.pitch=.82;u.volume=1;const voices=window.speechSynthesis.getVoices();const preferred=voices.find(v=>/^en-US/i.test(v.lang)&&/Daniel|Alex|Fred|Aaron/i.test(v.name))||voices.find(v=>/^en-US/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang));if(preferred)u.voice=preferred;window.speechSynthesis.speak(u);}catch(e){console.warn('ceremony speech failed',e);}}
function sportNoticeV010(title,sub='',tone=''){const feed=$('#sportFeed');if(!feed)return;const key=String(title)+'|'+String(sub),now=performance.now();if(key===lastSportKeyV010&&now-lastSportAtV010<140)return;lastSportKeyV010=key;lastSportAtV010=now;if((typeof ceremony!=='undefined')&&(ceremony==='practice'||ceremony==='match')){$('#feedback').textContent='';state.feedbackTime=0;}const row=document.createElement('div');row.className='sport-item '+tone;const b=document.createElement('b');b.textContent=title;row.appendChild(b);if(sub){const s=document.createElement('span');s.textContent=sub;row.appendChild(s);}feed.prepend(row);while(feed.children.length>3)feed.lastElementChild.remove();requestAnimationFrame(()=>row.classList.add('show'));setTimeout(()=>row.classList.add('leave'),1050);setTimeout(()=>row.remove(),1380);}
const _announceV010=announce;
announce=function(text,sub='',seconds=.75){const t=String(text||'');let title=t,tone='',route=false;if(t==='少し早い！'){title='TOO EARLY';tone='miss';route=true;}else if(t==='LOB'){title='EARLY · LOB';route=true;}else if(t==='DRIVE'){title='LATE · DRIVE';route=true;}else if(t==='PERFECT'||t.indexOf('PERFECT ×')===0){tone='perfect';route=true;}else if(t==='BODY RETURN'){tone='miss';route=true;}else if(t==='DOWN'){tone='down';route=true;}else if(t==='WAIT'){route=true;}else if(t==='PRACTICE'||t.indexOf('PRACTICE ')===0){tone='practice';route=true;}if(route){sportNoticeV010(title,sub,tone);return;}return _announceV010(text,sub,seconds);};
function queueRetryV010(){if(ceremony!=='match')return;retryQueueV010=retryQueueV010.filter(q=>!(q.target===state.target&&q.word===state.word));retryQueueV010.push({target:state.target,word:state.word,due:questionSerialV010+2});}
const _newQuestionV09=newQuestion;
newQuestion=function(){if(ceremony==='match'){questionSerialV010++;const i=retryQueueV010.findIndex(q=>q.due<=questionSerialV010);if(i>=0){const q=retryQueueV010.splice(i,1)[0];state.target=q.target;state.word=q.word;state.isRetry=true;lastWord[state.target]=state.word;$('#repeatWord').disabled=false;applyPracticeUI();return;}}state.isRetry=false;return _newQuestionV09();};
const _updatePracticeCardV09=updatePracticeCard;
updatePracticeCard=function(){const card=$('#practiceCard');if(ceremony==='match'&&answerCardTimerV010>0){card.hidden=false;card.setAttribute('aria-hidden','false');card.classList.add('answer-card');const ipa=WORD_IPA_V010[state.word]||('/'+SOUNDS[state.target].symbol+'/');card.innerHTML='<strong>'+state.word+'</strong><span>'+ipa+'</span><small>'+(answerCardCorrectV010?'正解':'正しくは')+' /'+SOUNDS[state.target].symbol+'/'+(state.isRetry?' · RETRY':'')+'</small>';return;}card.classList.remove('answer-card');return _updatePracticeCardV09();};
function showAnswerCardV010(correct){if(ceremony!=='match')return;answerCardCorrectV010=!!correct;answerCardTimerV010=correct?1.05:1.35;updatePracticeCard();}
const _sampleBallV09=sampleBall;
sampleBall=function(progress=state.flight/state.duration){if(ceremony==='time'&&progress>1){const r=Math.min(1,(progress-1)/.52),ease=1-Math.pow(1-r,2),targetZ=state.aimZ||0;return [-3.3-4.25*ease,.23+Math.abs(Math.sin(r*Math.PI*3.5))*.065*(1-r),targetZ+.34*ease];}return _sampleBallV09(progress);};
const _beginTimePassV09=beginTimePass;
beginTimePass=function(){const r=_beginTimePassV09();speakCallV010('Time!');return r;};
$('#bowBtn').addEventListener('click',()=>{if(ceremony==='bow-wait')bowWait=3.65;});
const _beginHajimeV09=beginHajime;
beginHajime=function(){const r=_beginHajimeV09();ceremonyTimer=.95;speakCallV010('Hajime!');return r;};
const _beginMatchV09=beginMatch;
beginMatch=function(){retryQueueV010=[];questionSerialV010=0;consecutiveFailsV010=0;answerCardTimerV010=0;knockdownV010=0;bodyHitV010=0;const feed=$('#sportFeed');if(feed)feed.textContent='';return _beginMatchV09();};
const _startV09=start;
start=function(){retryQueueV010=[];questionSerialV010=0;consecutiveFailsV010=0;answerCardTimerV010=0;knockdownV010=0;bodyHitV010=0;const feed=$('#sportFeed');if(feed)feed.textContent='';return _startV09();};
const _kickV09=kick;
kick=function(){const before=state.rally;const r=_kickV09();if(ceremony==='match'&&state.rally>before){consecutiveFailsV010=0;showAnswerCardV010(true);}return r;};
const _rescueV09=rescue;
rescue=function(kind){const before=state.misses,word=state.word,target=state.target;const r=_rescueV09(kind);if(ceremony==='match'&&state.misses>before&&state.mode!=='over'){queueRetryV010();consecutiveFailsV010++;player.kick=0;bodyHitV010=.62;state.flightStart=[player.n.pos[0]+.18,1.36,player.n.pos[2]];state.flight=0;previousBall=[...state.flightStart];showAnswerCardV010(false);const reason=kind==='symbol'?word+' → /'+SOUNDS[target].symbol+'/':kind==='early'?'少し早かった':'間に合わなかった';sportNoticeV010('BODY RETURN',reason+' · 体力 −'+CONFIG.missDamage,'miss');if(consecutiveFailsV010%3===0){knockdownV010=KNOCKDOWN_DURATION_V010;knockDirV010=state.misses%2?1:-1;state.hitstop=Math.max(state.hitstop,1.05);sportNoticeV010('DOWN',reason+' · 三連続ミス','down');audio.fail();}}return r;};
const _applyBowPoseV09=applyBowPose;
applyBowPose=function(){_applyBowPoseV09();if(bowAnim>0){const t=1-bowAnim/BOW_DURATION,k=Math.sin(Math.PI*Math.max(0,Math.min(1,t)));cpu.body.rot[2]-=k*.62;cpu.body.pos[1]-=k*.08;cpu.head.rot[2]+=k*.22;cpu.arm.rot[2]-=k*.14;cpu.farArm.rot[2]+=k*.10;}if(bodyHitV010>0){const k=Math.sin(bodyHitV010/.62*Math.PI);player.n.pos[0]-=k*.16;player.head.rot[2]+=k*.18;}if(knockdownV010>0){const t=1-knockdownV010/KNOCKDOWN_DURATION_V010,travel=Math.sin(Math.min(1,t/.72)*Math.PI/2),drop=Math.sin(Math.min(1,t/.58)*Math.PI/2);player.n.pos[2]+=knockDirV010*2.0*travel;player.body.pos[1]-=.48*drop;player.body.rot[0]+=knockDirV010*Math.PI*1.45*travel;player.body.rot[2]+=knockDirV010*.55*travel;player.arm.rot[2]-=knockDirV010*.9*travel;player.farArm.rot[2]+=knockDirV010*.7*travel;}};
const _updateGameV09=updateGame;
updateGame=function(dt){if(ceremony==='time'&&state.mode==='playing'){state.flight+=dt;state.aimZ+=(0-state.aimZ)*Math.min(1,dt*5);$('#time').textContent='--';if(state.flight>state.duration+1.18)enterTimeChoiceV09();return;}const r=_updateGameV09(dt);if(ceremony==='match'){if(answerCardTimerV010>0){answerCardTimerV010=Math.max(0,answerCardTimerV010-dt);if(answerCardTimerV010===0)updatePracticeCard();}bodyHitV010=Math.max(0,bodyHitV010-dt);knockdownV010=Math.max(0,knockdownV010-dt);}return r;};
`;
html=html.replace(marker,v010+'\n'+marker);
return html;
};
