'use strict';
// Default: original renderer matrices + geometry. --browser also verifies GPU pixels.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {vmFixture,sourceSeam,VIEWPORTS}=require('./complete-browser-v030.cjs');
const html=require('./assemble.cjs')().replace('render(root){const g=this.gl;','render(root){window.__foregroundEye=[...this.eye];const g=this.gl;');
const stages=['station','jingu','gendo','chion','sanjo','shinkyogoku','million','gion'];
function setup(q,stage,back=false){const doc=q.renderer.canvas.ownerDocument;doc.body.classList.remove('campaign-screen','campaign-cinematic');doc.querySelector('#campaignUI').hidden=true;doc.querySelector('#intro').hidden=true;for(const overlay of doc.querySelectorAll('.overlay'))overlay.hidden=true;q.campaign.phase='match';q.campaign.intro=stage==='station';q.state.mode='playing';q.duel.entered=back;q.duel.phase=back?'back':'front';q.duel.time=0;q.draw();}
function query(stage){return stage==='station'?'?intro=1':'?stage='+stage;}
function clip(poly,axis,sign){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=1-sign*a[axis],db=1-sign*b[axis];if(da>=0)out.push(a);if((da>=0)!==(db>=0)){const t=da/(da-db);out.push(a.map((v,j)=>v+(b[j]-v)*t));}}return out;}
function depthReport(draws){const mat=(m,p)=>[0,1,2].map(i=>m[i]*p[0]+m[i+4]*p[1]+m[i+8]*p[2]+m[i+12]);let farLandmarks=0,maxLandmarkDepth=0,farGround=0;for(const d of draws)for(let i=0;i<d.p.length;i+=9){const world=[0,3,6].map(j=>mat(d.uM,d.p.slice(i+j,i+j+3)));let poly=world.map(p=>mat(d.uVP,p));for(const axis of [0,1])for(const sign of [-1,1])poly=clip(poly,axis,sign);if(!poly.length)continue;const depth=(Math.max(...poly.map(p=>p[2]))+1)*99.9/2+.1;if(world.every(p=>p[1]<=.1)){if(depth>100.001)farGround++;}else{maxLandmarkDepth=Math.max(maxLandmarkDepth,depth);if(depth>100.001)farLandmarks++;}}return{farLandmarks,maxLandmarkDepth,farGround};}
function vmCheck(){let checks=0,maxRetreat=0,maxLandmarkDepth=0,farGround=0;for(const stage of stages){const f=vmFixture(html,{url:'http://foreground.test/'+query(stage)}),q=f.w.qa;for(const [width,height] of VIEWPORTS){f.resize(width,height);for(const back of [false,true]){setup(q,stage,back);const r=q.renderer,eye=r.eye,target=[...r.target],zoom=r.zoom;const after=Array.from(r.vp),renderEye=Array.from(f.w.__foregroundEye);maxRetreat=Math.max(maxRetreat,Math.hypot(...renderEye.map((v,i)=>v-eye[i])));assert.equal(r.eye,eye,'render restores the camera object');Object.getPrototypeOf(r).render.call(r,q.root);const before=Array.from(r.vp);for(const i of [0,1,4,5,8,9,12,13])assert(Math.abs(before[i]-after[i])<1e-5,'orthographic XY unchanged');assert.deepEqual([...r.target],target);assert.equal(r.zoom,zoom);r.render(q.root);assert.equal(r.eye,eye);const report=depthReport(f.gl.draws);assert.equal(report.farLandmarks,0,stage+' far plane clips a visible landmark');maxLandmarkDepth=Math.max(maxLandmarkDepth,report.maxLandmarkDepth);farGround+=report.farGround;checks++;}}
 // Exercise the lowered orbit camera at the most demanding portrait shape.
 f.resize(390,844);setup(q,stage,true);for(const time of [.4,.8,1.2,1.6,2.0,2.6,3.2]){q.duel.phase='break';q.duel.time=time;q.draw();const eye=q.renderer.eye,actual=f.w.__foregroundEye;maxRetreat=Math.max(maxRetreat,Math.hypot(...actual.map((v,i)=>v-eye[i])));const report=depthReport(f.gl.draws);assert.equal(report.farLandmarks,0,stage+' orbit far plane clips landmark');maxLandmarkDepth=Math.max(maxLandmarkDepth,report.maxLandmarkDepth);farGround+=report.farGround;checks++;}const renderEye=q.renderer.eye,clear=f.gl.clear;f.gl.clear=()=>{throw Error('expected render interruption')};assert.throws(()=>q.renderer.render(q.root),/expected render interruption/);assert.equal(q.renderer.eye,renderEye,'failed render restores camera');f.gl.clear=clear;f.close();}
 return{mode:'VM matrix/geometry',checks,maxRetreat,maxLandmarkDepth,farGroundTriangles:farGround};}
async function browserCheck(){const {chromium}=require('playwright'),browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const out=path.resolve(process.env.FEG_FOREGROUND_DIR||'../work/foreground-browser');fs.mkdirSync(out,{recursive:true});const context=await browser.newContext(),page=await context.newPage();await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;window.speechSynthesis.cancel();});await page.route('http://foreground.test/**',route=>route.fulfill({contentType:'text/html',body:sourceSeam(html)}));const results=[];
 try{for(const stage of stages){await page.goto('http://foreground.test/'+query(stage));await page.waitForFunction(()=>window.qa);for(const [width,height] of [[320,568],[390,844]]){await page.setViewportSize({width,height});for(const back of [false,true]){await page.evaluate(({stage,back,fn})=>(0,eval)('('+fn+')')(qa,stage,back),{stage,back,fn:setup.toString()});const result=await page.evaluate(()=>{const q=qa,r=q.renderer,g=r.gl,sky=kemari.getScenery().atmosphere.sky.map(v=>Math.round(v*255));function sample(){const pixels=new Uint8Array(g.drawingBufferWidth*10*4);g.readPixels(0,0,g.drawingBufferWidth,10,g.RGBA,g.UNSIGNED_BYTE,pixels);let clear=0,total=0;for(let i=0;i<pixels.length;i+=4){total++;if(sky.every((v,j)=>Math.abs(pixels[i+j]-v)<=1))clear++;}return{clear,total};}q.draw();const after=sample(),eye=[...r.eye],actual=[...window.__foregroundEye];Object.getPrototypeOf(r).render.call(r,q.root);const before=sample();r.render(q.root);const ext=g.getExtension('WEBGL_debug_renderer_info');return{before,after,eye,actual,error:g.getError(),renderer:ext?g.getParameter(ext.UNMASKED_RENDERER_WEBGL):g.getParameter(g.RENDERER)};});assert.equal(result.error,0);assert(result.after.clear/result.after.total<.01,stage+' '+width+' '+back+' foreground still sky: '+JSON.stringify(result));assert(!/swiftshader|software/i.test(result.renderer));results.push({stage,width,height,back,...result});if(width===390&&['station','million'].includes(stage)&&!back){await page.evaluate(()=>{const saved=qa.renderer.render;qa.renderer.render=Object.getPrototypeOf(qa.renderer).render;try{qa.draw()}finally{qa.renderer.render=saved}});await page.screenshot({path:path.join(out,stage+'-foreground-before-390x844.png')});await page.evaluate(()=>qa.draw());await page.screenshot({path:path.join(out,stage+'-foreground-after-390x844.png')});}}}}
 const report={passed:true,mode:'actual WebGL pixels',results};fs.writeFileSync(path.join(out,'foreground-browser-report.json'),JSON.stringify(report,null,2)+'\n');return{mode:report.mode,checks:results.length,renderer:results[0].renderer,regressionsReproduced:results.filter(r=>r.before.clear/r.before.total>.9).length,out};}finally{await browser.close();}}
(async()=>{const result=process.argv.includes('--browser')?await browserCheck():vmCheck();console.log(JSON.stringify({passed:true,...result},null,2));})().catch(error=>{console.error(error);process.exitCode=1});
