'use strict';
// Standalone scenery contract/geometry tests. Optional --render uses pngjs to
// create explicitly SOFTWARE-RENDERED review images; this is not WebGL evidence.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),OUT=path.resolve(__dirname,'../../feg-evidence/scenery');
const code=fs.readFileSync(path.join(ROOT,'scenery/kyoto-scenes.js'),'utf8');
const fnStart=code.indexOf(' function installKyotoSceneryV030(){'),fnEnd=code.lastIndexOf('\n};');
const install=code.slice(fnStart,fnEnd).trim();assert(install.endsWith('}'));
const base=Buffer.from([1,2,3,4,5].map(i=>fs.readFileSync(path.join(ROOT,'app'+i+'.b64'),'utf8')).join('').replace(/\s/g,''),'base64').toString('utf8');
const engine=[...base.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(x=>x.includes('class Renderer'));
assert(engine,'native GardenGL implementation');
function create(id,query='?stage='+id){const context={window:{location:{search:query}},URLSearchParams,console};vm.createContext(context);vm.runInContext(engine,context);for(const file of ['content/characters.js','content/stages.js','characters/seven-rigs.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,file),'utf8'),context);
 vm.runInContext(`const G=window.GardenGL,root=new G.Node(),frontSceneryV022=root.add(new G.Node()),backSceneryV022=root.add(new G.Node());
const geom={box:G.box(),ico:G.ico(),cyl:G.cylinder(1,1,8),cone:G.cylinder(0,1,5),robe:G.cylinder(.65,1,6),head:G.cylinder(.8,.9,6)};
function group(parent,pos=[0,0,0]){const n=new G.Node();n.pos=pos;parent.add(n);return n;}
function mesh(parent,shape,tint,pos=[0,0,0],scale=[1,1,1],rot=[0,0,0],unlit=0){const n=new G.Node(typeof shape==='string'?geom[shape]:shape,tint);n.pos=pos;n.scale=scale;n.rot=rot;n.unlit=unlit;parent.add(n);return n;}
const ACTIVE_STAGE={id:${JSON.stringify(id)}};let sceneryV030,visualTime=0,motion=true,testBack=false,testYaw=null;const state={mode:'playing',rally:10};const renderer={eye:[1.25,5.6,17],target:[0,2,0],zoom:1,gl:{clearColor(...c){renderer.sky=c}}};
let prepareDepthRenderV022=()=>{frontSceneryV022.visible=!testBack;backSceneryV022.visible=testBack;const a=testYaw===null?(testBack?.303:.073):testYaw,z=testBack?-8:0;renderer.eye=[Math.sin(a)*17,5.6,z+Math.cos(a)*17];renderer.target=[0,2,z];};
(${install})();
const stage=window.FEGContent.stages.find(s=>s.id===ACTIVE_STAGE.id)||window.FEGContent.stages[0];const playerCharacter=window.FEGContent.characters.find(c=>c.id===stage.player),opponentCharacter=window.FEGContent.characters.find(c=>c.id===stage.opponent);
const actors=[window.FEGCharacterRigs.seven({root,group,mesh},-4.4,playerCharacter.appearance,1),window.FEGCharacterRigs.seven({root,group,mesh},4.4,opponentCharacter.appearance,-1)];
window.test={root,renderer,state,actors,read:()=>sceneryV030.describe(),draw(back=false,yaw=null){testBack=back;testYaw=yaw;for(const actor of actors)actor.n.pos[2]=back?-8:0;prepareDepthRenderV022();},tick(dt){visualTime+=dt;prepareDepthRenderV022()},motion(on){motion=on}};window.test.draw();`,context);return context.window.test;}
function walk(n,fn){fn(n);n.children.forEach(c=>walk(c,fn));}
function transform(p,n){let [x,y,z]=p.map((v,i)=>v*n.scale[i]);const[a,b,c]=n.rot;[y,z]=[y*Math.cos(a)-z*Math.sin(a),y*Math.sin(a)+z*Math.cos(a)];[x,z]=[x*Math.cos(b)+z*Math.sin(b),-x*Math.sin(b)+z*Math.cos(b)];[x,y]=[x*Math.cos(c)-y*Math.sin(c),x*Math.sin(c)+y*Math.cos(c)];return[x+n.pos[0],y+n.pos[1],z+n.pos[2]];}
const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>a.map(v=>v/(Math.hypot(...a)||1));
function raster(test,width=768,height=432){const {PNG}=require('pngjs'),png=new PNG({width,height}),depth=new Float64Array(width*height);depth.fill(Infinity);const r=test.renderer,sky=r.sky||[.3,.4,.5],z=unit(sub(r.eye,r.target)),x=unit(cross([0,1,0],z)),y=cross(z,x),w=Math.max(12.3,width/height*6.8)/(r.zoom||1),h=w/(width/height),light=unit([-.5,.85,.65]);
 for(let i=0;i<width*height;i++){for(let c=0;c<3;c++)png.data[i*4+c]=sky[c]*255;png.data[i*4+3]=255;}
 const project=p=>{const d=sub(p,r.target);return[(dot(d,x)/w+.5)*width,(.5-dot(d,y)/h)*height,dot(sub(p,r.eye),z)];};
 let triangles=0;
 function visit(n,parents=[]){if(!n.visible)return;const chain=[n,...parents];if(n.geo){const g=n.geo;for(let i=0;i<g.p.length;i+=9){const pts=[];for(let a=0;a<3;a++){let p=Array.from(g.p.slice(i+a*3,i+a*3+3));for(const nd of chain)p=transform(p,nd);pts.push(p);}const pr=pts.map(project),normal=unit(cross(sub(pts[1],pts[0]),sub(pts[2],pts[0]))),lit=n.unlit?1:.56+.44*Math.max(dot(normal,light),0),center=pts[0].map((v,c)=>(v+pts[1][c]+pts[2][c])/3);let f=Math.max(0,Math.min(1,(Math.hypot(center[0],center[2]-(r.fogCenter||0))-10)/32));f=f*f*(3-2*f)*(r.fogStrength??.72);const color=[0,1,2].map(c=>{const cc=g.c?g.c[i+c]:1;return Math.round(255*((n.color[c]*cc*lit)*(1-f)+(r.fogColor||sky)[c]*f));});
 const minX=Math.max(0,Math.ceil(Math.min(...pr.map(p=>p[0])))),maxX=Math.min(width-1,Math.floor(Math.max(...pr.map(p=>p[0])))),minY=Math.max(0,Math.ceil(Math.min(...pr.map(p=>p[1])))),maxY=Math.min(height-1,Math.floor(Math.max(...pr.map(p=>p[1]))));if(minX>maxX||minY>maxY)continue;const[a,b,c]=pr,den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-9)continue;triangles++;
 for(let py=minY;py<=maxY;py++)for(let px=minX;px<=maxX;px++){const u=((b[1]-c[1])*(px-c[0])+(c[0]-b[0])*(py-c[1]))/den,v=((c[1]-a[1])*(px-c[0])+(a[0]-c[0])*(py-c[1]))/den,t=1-u-v;if(u<0||v<0||t<0)continue;const d=-(u*a[2]+v*b[2]+t*c[2]),idx=py*width+px;if(d>=depth[idx])continue;depth[idx]=d;for(let q=0;q<3;q++)png.data[idx*4+q]=color[q];}}
 }for(const child of n.children)visit(child,chain);}visit(test.root);return{png:PNG.sync.write(png),triangles};}
function main(){const output=process.argv.includes('--render'),summary=[];if(output)fs.mkdirSync(OUT,{recursive:true});for(const id of ['jingu','gendo','chion','sanjo','shinkyogoku','million','gion','station']){const t=create(id,id==='station'?'?intro=1':'?stage='+id),m=t.read();assert.equal(m.id,id);assert(m.vertices.every(n=>n>1000&&n<250000),'bounded substantive scene '+id);assert(m.staticBatches.every(n=>n<60),'bounded batches '+id);assert(m.dynamicNodes<=70);let nodes=0;walk(t.root,n=>{nodes++;for(const value of [...n.pos,...n.rot,...n.scale])assert(Number.isFinite(value));if(n.geo){for(const value of n.geo.p)assert(Number.isFinite(value));assert.equal(n.geo.p.length,n.geo.n.length);}});for(const back of [false,true]){t.draw(back);assert.equal(t.read().side,back?'back':'front');const initial=JSON.stringify(t.root);t.state.mode='paused';const time=t.read().animationTime;t.tick(.1);assert.equal(t.read().animationTime,time,'paused environmental animation');t.state.mode='playing';t.motion(false);t.tick(.1);assert.equal(t.read().animationTime,time,'reduced-motion environmental animation');t.motion(true);t.tick(.1);assert(t.read().animationTime>time);for(let i=0;i<24;i++){t.draw(back,i*Math.PI/12);const s=t.read();assert(s.visibleModules.length>0);assert(s.atmosphere.fog.every(Number.isFinite));}t.draw(back);if(output){const frame=raster(t);fs.writeFileSync(path.join(OUT,id+'-'+(back?'back':'front')+'-software.png'),frame.png);}}
 let after=0;walk(t.root,()=>after++);assert.equal(after,nodes,'animation never allocates scene nodes');if(id==='gendo'){assert.equal(m.statues.front,0);assert.equal(m.statues.back,69);}if(id==='shinkyogoku')assert(m.landmarks.includes('left-airplane-sculpture')&&m.landmarks.includes('curved-yellow-canopy'));summary.push(m);console.log('PASS scenery',id,JSON.stringify({vertices:m.vertices,batches:m.staticBatches,dynamic:m.dynamicNodes}));}
 assert.equal(create('jingu','').read().id,'station');assert.equal(create('jingu','?view=garden').read().id,'jingu');assert.equal(create('first-court','?stage=first-court').read().id,'jingu');assert.equal(create('second-court','?stage=second-court').read().id,'sanjo');if(output)fs.writeFileSync(path.join(OUT,'scenery-software-report.json'),JSON.stringify({renderer:'software reference rasterization; NOT WebGL or device proof',scenes:summary},null,2));console.log('PASS native geometry: eight scene pairs, 360-degree cutaway, stage origins, bounded pools, paused/reduced motion, source features and aliases');}
module.exports={create,raster};if(require.main===module)main();
